### ISSUE TITLE
questions about test dataset

### ISSUE THREAD

**Issue by Gucci233** [Lu-Feng/CricaVPR#11]
Hello, I used the testing program for Pitts30k in NetVLAD and used the weight file you provided to reduce the dimensionality to 4096 using PCA. The results I obtained seem to be inconsistent with those in the paper. Is there a problem with the dataset?
R@1: 88.0, R@5: 94.7, R@10: 96.6, R@20: 97.4

**Comment by Lu-Feng** [comment]
Hello, Do you mean you only used our model weight but the testing program was different from ours?

**Comment by Gucci233** [comment]
是的，但是现在我使用了你们的程序，得到了一个相近的结果，谢谢

**Comment by Gucci233** [comment]
Yes, but now I have used your program and obtained a similar result. Thank you
