### ISSUE TITLE
 Releasing the model on torch.hub?

### ISSUE THREAD

**Issue by gmberton** [Lu-Feng/CricaVPR#2]
Hi, thank you for uploading the code and trained models!
Could you release the model on torch.hub? It is quite simple to do and allows people to use your model with two lines of code, allowing more people to use your model and helping to spread your work!
For example I did it for CosPlace, and the trained model can be automatically downloaded from anywhere without cloning the repo just like this
```
import torch
model = torch.hub.load("gmberton/cosplace", "get_trained_model", backbone="ResNet50", fc_output_dim=2048)
```
so it would be easier for everyone to use and I could also add it to [this benchmarking repo](https://github.com/gmberton/VPR-methods-evaluation).

PS: I really like the focus on small dimensional features, congrats on the paper!

**Comment by Lu-Feng** [comment]
@gmberton Hello, many thanks for your recognition of our work. I've added a hubconf.py to the repo and you can use the trained model as

```
import torch
model = torch.hub.load("Lu-Feng/CricaVPR", "trained_model")
```

However, I am not sure whether our work is suitable to be added to the VPR-methods-evaluation repo. Our method requires setting the batchsize to 16 (and 8 for Pitts30k/Pitts250k) during inference to reproduce the results. The image resolution we set is 224x224. Our low-dimensional features are obtained using PCA (optional during inference, following visual-geo-localization-benchmark), and the original dimension is 14x768. The currently trained model does not contain PCA transformation. We will continue to improve our code.

**Comment by gmberton** [comment]
Thanks for the reply!
Regarding batch size, I think it shouldn't matter for inference?
Changing the resolution is fine in our codebase, also other model (like SALAD) use different resolutions.
I'll be waiting for the model with PCA as well!

**Comment by hit2sjtu** [comment]
I am also wondering the impact of query batch size on final results. Does it matter much? In practice, single query retrieval is prefered. @Lu-Feng

**Comment by Lu-Feng** [comment]
@hit2sjtu Setting batchsize=1 during inference will bring about 1%-3% R@1 performance reduction. I found that there are two possible reasons:  First, setting batchsize=1 makes our cross-image encoder ineffective during testing, which leads to gaps between training and testing. Secondly, in some test datasets, different images (such as different views) from the same place are loaded into the same batch during inference, which allows the cross-image encoder to improve viewpoint invariance when producing the representation of a certain image. The former may be alleviated by some means. The latter does limit the performance of our method in some practices.

**Comment by Lu-Feng** [comment]
@hit2sjtu  For example, on the MSLS-val dataset, setting batchsize=1 causes the result of our method (R@1/R@5) to decrease from 90.0/95.4 to 89.1/95.3. (The result of the ablation experiment without our cross-image encoder in both training and inference is 85.5/93.2). On MSLS-challenge, they decrease from 69.0/82.1 to 66.9/79.3. For this dataset, there are no two images from the same place in a inference batch of query data, the performance degradation is not due to the second reason. I think it is due to the gap in training and testing, and can be addressed in some ways (we plan to do it in the next time).

**Comment by hit2sjtu** [comment]
> @hit2sjtu Setting batchsize=1 during inference will bring about 1%-3% R@1 performance reduction. I found that there are two possible reasons: First, setting batchsize=1 makes our cross-image encoder ineffective during testing, which leads to gaps between training and testing. Secondly, in some test datasets, different images (such as different views) from the same place are loaded into the same batch during inference, which allows the cross-image encoder to improve viewpoint invariance when producing the representation of a certain image. The former may be alleviated by some means. The latter does limit the performance of our method in some cases.

Thanks for the clarification. @Lu-Feng I agree with your analysis.

I did some quick test on amstertime at first. but the results are hard to understand.

I guess bs=1 works worst,while other results are kind of random.

amstertime

bs = 16
2024-03-22 18:04:06   Recalls on < BaseDataset, amstertime - #database: 1231; #queries: 1231 >: R@1: 64.3, R@5: 82.4, R@10: 87.2, R@100: 97.1
bs = 8
2024-03-22 18:04:30   Recalls on < BaseDataset, amstertime - #database: 1231; #queries: 1231 >: R@1: 68.0, R@5: 85.3, R@10: 89.3, R@100: 97.6
bs =4
2024-03-22 18:05:19   Recalls on < BaseDataset, amstertime - #database: 1231; #queries: 1231 >: R@1: 72.5, R@5: 87.4, R@10: 90.9, R@100: 97.
bs=2
2024-03-22 18:06:07   Recalls on < BaseDataset, amstertime - #database: 1231; #queries: 1231 >: R@1: 73.6, R@5: 87.7, R@10: 90.6, R@100: 98.3
bs=1
2024-03-22 18:06:53   Recalls on < BaseDataset, amstertime - #database: 1231; #queries: 1231 >: R@1: 49.8, R@5: 70.9, R@10: 76.6, R@100: 93.9

**Comment by Lu-Feng** [comment]
@hit2sjtu  Thank you for providing the results on AmsterTime. These results do seem incomprehensible. We didn't realize the impact of batchsize in inference at the beginning. We just set batchsize=16. Since the inference on Pitts30k is implemented in train.py, which uses 2GPU, i.e. the same as batchsize=8 on one GPU. The fluctuations in results of AmsterTime look quite large. This is a very special dataset, and conducting such experiments on other datasets may be more helpful to analyze the reasons. Besides, the results don't seem to be completely random when bs>1. We need more time to analyze the reason, but I'm busy with other things recently and we can open a new issue to discuss this at the end of this month. You can also add me on wechat 1600925872.

**Comment by gmberton** [comment]
These results are quite interesting. I think adding an ablation to the supplementary would be really useful, and it shouldn't take much to run inference with different batch sizes

**Comment by Lu-Feng** [comment]
Hi, @gmberton @hit2sjtu . Sorry for the delay. We have added an ablation to the supplementary and mentioned this in Limitations. The arXiv version of final paper is expected to be announced tomorrow. We have conducted experiments on several datasets. An inference batch size that is too small (e.g., 2 or 4) will lead to unstable results. Although the inference batch size that achieves the best performance on different datasets does not appear to be fixed (increase or decrease it will gradually reduce performance), setting it to 16 (values from 8 to 32 are also ok) can achieve good results on all datasets.

**Comment by Lu-Feng** [comment]
We suspect that loading images from different places in an inference batch doesn’t always enhance (or, in some cases, reduce) the robustness of each other. Therefore, an inference batch size that is too small will lead to unstable results. When there are enough images in an inference batch, this randomness will be reduced, or modeling the correlation of enough images will help eliminate the (negative) impact of individual special images (after all, the batch size in training is much larger than that in inference).

**Comment by gmberton** [comment]
Thank you for the reply and for adding the ablation!
