### ISSUE TITLE
How you generate the feature map in Fig.6?

### ISSUE THREAD

**Issue by shuimushan** [Lu-Feng/CricaVPR#3]
Thanks for sharing your work! I wonder how you generate the visualization of feature maps in Fig.6 in the paper. Could you please give some detailed explanation of it (about which layer you used, how you combine the features and so on) or would you release relevant code?

**Comment by Lu-Feng** [comment]
Hello, thanks for your interest in our work. We reshape the output patch tokens of the ViT backbone (you can also use the attention value of the last Transformer block) as W*H*C-dim feature map, then compute the mean in the channel dimension of the feature map and display it using the heat map. Note that Figure 6 in the paper is the result of the model only using our MulConvAdapter (without cross-image encoder).

**Comment by shuimushan** [comment]
Thanks! I got it.

**Comment by nobeldang** [comment]
Hi, can you explain why taking the mean of channel dimension (e.g 768 dim) of the output from transformer will give us attention map? Am I missing something here?
Also, can you share the code you used for the visualization?
Thanks

**Comment by ganshanliushui678** [comment]
> Thanks! I got it.

hello! Have you reproduce the figure 6 successfully? I reproduce the official  DINOV2 successfully,  but using the same method I can't reproduce the adpated DINOV2, looking for your reply.
