### ISSUE TITLE
Can you provide the dataset.py files for the msls dataset and the Tokyo 24/7 dataset

### ISSUE THREAD

**Issue by YunLi-AI** [Lu-Feng/CricaVPR#5]
Can you provide the dataset.py files for the msls dataset and the Tokyo 24/7 dataset

**Comment by Lu-Feng** [comment]
Hello, thanks for your interest in our work. We used this repository (https://github.com/gmberton/VPR-datasets-downloader) to download and format datasets. Besides, we use the official version of [MSLS-val](https://github.com/mapillary/mapillary_sls) (only contains 740 query images) for testing, which is a subset of the MSLS-val formated by VPR-datasets-downloader (contains about 11k query images). More detail can be found [here](https://github.com/Lu-Feng/SelaVPR/issues/1). The key (name) of query images of official MSLS-val can be obtained [here](https://github.com/Lu-Feng/MSLS-val). You can copy official 740 query images from the query images downloaded using VPR-datasets-downloader based on the key/name. You can also add me on WeChat (1600925872) if you need more help.

**Comment by YunLi-AI** [comment]
谢谢你愿意提供帮助，这个是你QQ号吗，在微信上搜了下，昵称是一个句号吗，加了下
![R-C](https://github.com/Lu-Feng/CricaVPR/assets/50945287/0a6d549a-6a7a-45f7-9158-8afabe68363a)
