### ISSUE TITLE
Could you please give me some help about the NordLand dataset?

### ISSUE THREAD

**Issue by Fragmentszz** [Lu-Feng/CricaVPR#6]
I found the model preform very bad when using NordLand dataset while performing very good in other datasets, I download the dataset from [here](https://universityofadelaide.app.box.com/s/zkfk1akpbo5318fzqmtvlpp7030ex4up) because the download url of this dataset in [https://github.com/gmberton/VPR-datasets-downloader](https://github.com/gmberton/VPR-datasets-downloader) has been unavailable. Then I also use the left part of [download_nordland.py](https://github.com/gmberton/VPR-datasets-downloader/blob/main/download_nordland.py) to format this dataset. However, the eval result is very unsatisfying. Could you please give some help about Nordland dataset?

**Comment by Lu-Feng** [comment]
I guess that you got the wrong label (image name) when you formatted the downloaded dataset with [download_nordland.py](https://github.com/gmberton/VPR-datasets-downloader/blob/main/download_nordland.py). Could you provide the names of the first ten images in database/queries.

**Comment by Fragmentszz** [comment]
In database or queries they are all:
@0@0.0
@0@2.3
@0@4.7
@0@7.1
@0@9.5
@0@11.9
@0@14.2
@0@16.6
@0@19.0
@0@21.4
However, I find the name of original image in Winter is image-00002.png, image-00007.png, image-00015.png $\cdots$(noncontinuous) while the original image in Summer is image-00001.png, image-00002.png, image-000003.png $\cdots$(continuous).
May the ```utm_north``` in [download_nordland.py](https://github.com/gmberton/VPR-datasets-downloader/blob/main/download_nordland.py) should be caculated by the noncontinuous images id instead of the ```num_image``` which is added one each time?

**Comment by Fragmentszz** [comment]
Just now I tried use Fall as the queries which also contains the continuous image ids and use Summer as the database, the result is  fairly good, I suppose maybe there are some images omitted in my Winter dataset.

**Comment by Lu-Feng** [comment]
The names of the first ten images in database seem right. If there are some images omitted in the Winter dataset, it can also result in incorrect labels being generated through [download_nordland.py](https://github.com/gmberton/VPR-datasets-downloader/blob/main/download_nordland.py). There should be the same number of images in the database and queries.

**Comment by Fragmentszz** [comment]
OK, I see. The Winter dataset only contains 8970 pictures while the Fall and the Summer contains 35768 pictures. That's the reason. Thanks! :)
