### ISSUE TITLE
Questions for DINOv2

### ISSUE THREAD

**Issue by Gucci233** [Lu-Feng/CricaVPR#8]
Hello,how does your code reduce features dim to 512,1024 after importing DINOv2? Gem pooling or adding a linear layer?

**Comment by Lu-Feng** [comment]
Hello, we don't use the linear layer to reduce the feature dimension. GeM pooling is used to aggregate all 768-D patch features in each image region into a 768-D vector. We concatenate 14 region (GeM) features and get 14*768-D image representation. PCA is optional for dimension reduction (to 512, 1024, or 4096, etc).
